services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
      - /app/dist
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npx prisma db seed && npm run dev"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5532:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
